Script started on Tue 26 Jan 2016 01:20:04 PM EST
bash-4.1$ cd ![K~/os161/root
bash-4.1$ sys161 [K[K[K[K[K[K[Kos161-gdb kernel
GNU gdb 6.6
Copyright (C) 2006 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "--host=x86_64-unknown-linux-gnu --target=mips-harvard-os161"...
(gdb) dir ../os161-2.0/kern/compile/ASST2
Source directories searched: /home/psu2/os161/root/../os161-2.0/kern/compile/ASST2:$cdir:$cwd
(gdb) target remote unix:.sockets/gdb
Remote debugging using unix:.sockets/gdb
[New Thread 10]
__start () at ../../arch/sys161/main/start.S:54
54	   addiu sp, sp, -24
Current language:  auto; currently asm
(gdb) break menu
Breakpoint 1 at 0x80015778: file ../../main/menu.c, line 731.
(gdb) where[K[K[K[K[Kc
Continuing.

Breakpoint 1, menu (args=0x800373c0 "") at ../../main/menu.c:731
731		menu_execute(args, 1);
Current language:  auto; currently c
(gdb) where
#0  menu (args=0x800373c0 "") at ../../main/menu.c:731
#1  0xffffffff80014660 in kmain (arguments=0x800373c0 "")
    at ../../main/main.c:214
#2  0xffffffff8002ef3c in __start () at ../../arch/sys161/main/start.S:216
(gdb) detach
Ending remote debugging.
(gdb) quit
bash-4.1$ exit
exit

Script done on Tue 26 Jan 2016 01:22:19 PM EST
